<a href="https://colab.research.google.com/github/Preeti06100/pandas/blob/main/Labsheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

def add(x, y):
    return np.add(x, y)

def subtract(x, y):
    return np.subtract(x, y)

def multiply(x, y):
    return np.multiply(x, y)

def divide(x, y):
    if y != 0:
        return np.divide(x, y)
    else:
        return "Error! Division by zero."

def main():
    print("Welcome to the Simple NumPy Calculator!")
    while True:
        print("\nSelect operation:")
        print("1. Add")
        print("2. Subtract")
        print("3. Multiply")
        print("4. Divide")
        print("5. Exit")

        choice = input("Enter choice (1/2/3/4/5): ")

        if choice == '5':
            print("Exiting the calculator.")
            break

        try:
            num1 = float(input("Enter first number: "))
            num2 = float(input("Enter second number: "))
        except ValueError:
            print("Invalid input! Please enter a valid number.")
            continue

        if choice == '1':
            print(f"{num1} + {num2} = {add(num1, num2)}")

        elif choice == '2':
            print(f"{num1} - {num2} = {subtract(num1, num2)}")

        elif choice == '3':
            print(f"{num1} * {num2} = {multiply(num1, num2)}")

        elif choice == '4':
            print(f"{num1} / {num2} = {divide(num1, num2)}")

        else:
            print("Invalid input! Please choose a valid operation.")

if __name__ == "__main__":
    main()


Welcome to the Simple NumPy Calculator!

Select operation:
1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit
Enter choice (1/2/3/4/5): 1
Enter first number: 20
Enter second number: 40
20.0 + 40.0 = 60.0

Select operation:
1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit
Enter choice (1/2/3/4/5): 2
Enter first number: 30
Enter second number: 20
30.0 - 20.0 = 10.0

Select operation:
1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit
Enter choice (1/2/3/4/5): 3
Enter first number: 20
Enter second number: 40
20.0 * 40.0 = 800.0

Select operation:
1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit
Enter choice (1/2/3/4/5): 4
Enter first number: 60
Enter second number: 80
60.0 / 80.0 = 0.75

Select operation:
1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit
Enter choice (1/2/3/4/5): 5
Exiting the calculator.


In [4]:
import numpy as np
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a1D)
print(a2D)
print(a3D)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
import numpy as np

# Convert list to NumPy array
def list_to_array(lst):
    return np.array(lst)

# Convert tuple to NumPy array
def tuple_to_array(tpl):
    return np.array(tpl)

# Convert NumPy array to list
def array_to_list(arr):
    return arr.tolist()

# Convert NumPy array to tuple
def array_to_tuple(arr):
    return tuple(arr)


def main():

    sample_list = [1, 2, 3, 4, 5]
    sample_tuple = (10, 20, 30, 40, 50)

    print("Original List:", sample_list)
    print("Original Tuple:", sample_tuple)


    numpy_array_from_list = list_to_array(sample_list)
    print("\nList to NumPy Array:", numpy_array_from_list)


    numpy_array_from_tuple = tuple_to_array(sample_tuple)
    print("Tuple to NumPy Array:", numpy_array_from_tuple)


    list_from_array = array_to_list(numpy_array_from_list)
    print("\nNumPy Array back to List:", list_from_array)


    tuple_from_array = array_to_tuple(numpy_array_from_tuple)
    print("NumPy Array back to Tuple:", tuple_from_array)

if __name__ == "__main__":
    main()


Original List: [1, 2, 3, 4, 5]
Original Tuple: (10, 20, 30, 40, 50)

List to NumPy Array: [1 2 3 4 5]
Tuple to NumPy Array: [10 20 30 40 50]

NumPy Array back to List: [1, 2, 3, 4, 5]
NumPy Array back to Tuple: (10, 20, 30, 40, 50)


In [9]:
import numpy as np

def create_arrays():

    arr_arange = np.arange(0, 10, 2)
    print("Array created using np.arange():", arr_arange)
    arr_ones = np.ones((3, 4))
    print("\nArray created using np.ones():\n", arr_ones)
    arr_zeros = np.zeros((2, 5))
    print("\nArray created using np.zeros():\n", arr_zeros)


    arr_linspace = np.linspace(0, 1, 5)
    print("\nArray created using np.linspace():", arr_linspace)


    arr_eye = np.eye(4)
    print("\nArray created using np.eye():\n", arr_eye)

    arr_full = np.full((2, 3), 7)
    print("\nArray created using np.full():\n", arr_full)


    arr_random = np.random.rand(2, 3)
    print("\nArray created using np.random.rand():\n", arr_random)

if __name__ == "__main__":
    create_arrays()


Array created using np.arange(): [0 2 4 6 8]

Array created using np.ones():
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array created using np.zeros():
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Array created using np.linspace(): [0.   0.25 0.5  0.75 1.  ]

Array created using np.eye():
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Array created using np.full():
 [[7 7 7]
 [7 7 7]]

Array created using np.random.rand():
 [[0.31617462 0.84953504 0.34762988]
 [0.46959045 0.45453417 0.92111853]]


In [12]:
import numpy as np

def demonstrate_array_operations():

    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    arr3 = np.array([[1, 2], [3, 4]])

    print("Original Arrays:")
    print("arr1:", arr1)
    print("arr2:", arr2)
    print("arr3:\n", arr3)


    arr1_tiled = np.tile(arr1, 3)
    print("\nArray after np.tile() replication:", arr1_tiled)


    arr1_repeated = np.repeat(arr1, 2)
    print("Array after np.repeat() replication:", arr1_repeated)
    arr_concatenated = np.concatenate((arr1, arr2))
    print("\nArray after np.concatenate():", arr_concatenated)


    arr_stacked = np.stack((arr1, arr2))
    print("Array after np.stack():\n", arr_stacked)


    arr_hstacked = np.hstack((arr1, arr2))
    print("Array after np.hstack():", arr_hstacked)


    arr_vstacked = np.vstack((arr1, arr2))
    print("Array after np.vstack():\n", arr_vstacked)


    arr_mutated_add = arr1 + 10
    print("\nArray after mutation (add 10 to each element):", arr_mutated_add)


    arr3[0, 1] = 10
    print("Array arr3 after in-place mutation:\n", arr3)

if __name__ == "__main__":
    demonstrate_array_operations()


Original Arrays:
arr1: [1 2 3]
arr2: [4 5 6]
arr3:
 [[1 2]
 [3 4]]

Array after np.tile() replication: [1 2 3 1 2 3 1 2 3]
Array after np.repeat() replication: [1 1 2 2 3 3]

Array after np.concatenate(): [1 2 3 4 5 6]
Array after np.stack():
 [[1 2 3]
 [4 5 6]]
Array after np.hstack(): [1 2 3 4 5 6]
Array after np.vstack():
 [[1 2 3]
 [4 5 6]]

Array after mutation (add 10 to each element): [11 12 13]
Array arr3 after in-place mutation:
 [[ 1 10]
 [ 3  4]]


In [13]:
import numpy as np

def read_arrays_from_disk():

    try:

        arr_txt = np.loadtxt('data.txt')
        print("Array read from 'data.txt':\n", arr_txt)
    except OSError as e:
        print(f"Error reading 'data.txt': {e}")
    try:

        arr_csv = np.genfromtxt('data.csv', delimiter=',')
        print("\nArray read from 'data.csv':\n", arr_csv)
    except OSError as e:
        print(f"Error reading 'data.csv': {e}")


    try:

        arr_npy = np.load('data.npy')
        print("\nArray read from 'data.npy':\n", arr_npy)
    except OSError as e:
        print(f"Error reading 'data.npy': {e}")


    try:

        with np.load('data.npz') as data:
            arr1 = data['arr1']
            arr2 = data['arr2']
            print("\nArrays read from 'data.npz':")
            print("arr1:\n", arr1)
            print("arr2:\n", arr2)
    except OSError as e:
        print(f"Error reading 'data.npz': {e}")

if __name__ == "__main__":
    read_arrays_from_disk()


Error reading 'data.txt': data.txt not found.
Error reading 'data.csv': data.csv not found.
Error reading 'data.npy': [Errno 2] No such file or directory: 'data.npy'
Error reading 'data.npz': [Errno 2] No such file or directory: 'data.npz'


In [14]:
import numpy as np

def create_arrays_from_raw_bytes():

    byte_data = bytes([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    arr_from_buffer = np.frombuffer(byte_data, dtype=np.uint8)
    print("Array created from raw bytes using np.frombuffer:\n", arr_from_buffer)


    byte_string = b"1 2 3 4 5 6 7 8 9 10"
    arr_from_buffer_string = np.frombuffer(byte_string, dtype=np.uint8)
    print("\nArray created from raw byte string using np.frombuffer:\n", arr_from_buffer_string)


    byte_data_custom = bytes([1, 0, 0, 0, 2, 0, 0, 0])
    arr_from_custom_bytes = np.frombuffer(byte_data_custom, dtype=np.int32)
    print("\nArray created from raw bytes (custom dtype) using np.frombuffer:\n", arr_from_custom_bytes)


    raw_string = "1 2 3 4 5 6 7 8 9 10"
    arr_from_string = np.fromstring(raw_string, dtype=int, sep=" ")
    print("\nArray created from raw string using np.fromstring:\n", arr_from_string)

if __name__ == "__main__":
    create_arrays_from_raw_bytes()


Array created from raw bytes using np.frombuffer:
 [ 1  2  3  4  5  6  7  8  9 10]

Array created from raw byte string using np.frombuffer:
 [49 32 50 32 51 32 52 32 53 32 54 32 55 32 56 32 57 32 49 48]

Array created from raw bytes (custom dtype) using np.frombuffer:
 [1 2]

Array created from raw string using np.fromstring:
 [ 1  2  3  4  5  6  7  8  9 10]


In [15]:
import numpy as np

def demonstrate_random_functions():
    rand_uniform = np.random.rand(5)

    print("Random numbers from uniform distribution [0, 1):\n", rand_uniform)


    rand_normal = np.random.randn(3, 4)
    print("\nRandom numbers from standard normal distribution (mean=0, std=1):\n", rand_normal)


    rand_integers = np.random.randint(10, 50, size=5)
    print("\nRandom integers between 10 and 50:\n", rand_integers)


    arr = np.array([10, 20, 30, 40, 50])
    rand_sample = np.random.choice(arr, size=3, replace=False)
    print("\nRandomly sampled elements from an array:\n", rand_sample)


    np.random.shuffle(arr)
    print("\nArray after shuffle:\n", arr)
    np.random.seed(42)
    random_numbers_with_seed = np.random.rand(3)
    print("\nRandom numbers with seed 42 (reproducible):\n", random_numbers_with_seed)

if __name__ == "__main__":
    demonstrate_random_functions()


Random numbers from uniform distribution [0, 1):
 [0.0108451  0.30439558 0.40617137 0.36703361 0.20654641]

Random numbers from standard normal distribution (mean=0, std=1):
 [[ 0.31391639  0.04796963  0.34288944 -0.76368448]
 [ 0.50668605 -1.09617978 -0.28710865 -1.28818394]
 [-0.8111117   0.14393086  0.91444807 -0.13708576]]

Random integers between 10 and 50:
 [46 15 49 23 40]

Randomly sampled elements from an array:
 [50 20 10]

Array after shuffle:
 [30 20 50 40 10]

Random numbers with seed 42 (reproducible):
 [0.37454012 0.95071431 0.73199394]
